modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "mgmc_example"
version = "${version}"
displayName = "mgmc_example"
authors = "aixiaoji"
description = '''
mgmc_example
'''
#logoFile = ""

[[dependencies.mgmc_example]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mgmc_example]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mgmc_example]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "mgmc_example.mixins.json"
